### PR TITLE
migrating to kubernetes 1.30

### PR DESCRIPTION
**Pull request by averyniceday**

### CODE REVIEW

**Comment by leexgh** [comment]
@averyniceday GNAP mongodb is still on `eks-genome-nexus`, do we need to switch?
image

**Review by leexgh — COMMENTED** [review]
@averyniceday GNAP mongodb is still on `eks-genome-nexus`, do we need to switch?
image

**Review by dippindots — APPROVED** [review]
cbioportal-related changes look good to me

**Comment by dippindots** [comment]
@averyniceday Should I merge this?

**Comment by averyniceday** [comment]
@dippindots yes please!

**Comment by averyniceday** [comment]
@leexgh -- for the GNAP, I think some of our internal pipelines are running against the internal genome nexus. I'm still tracing which one we can decommission. I'm leaning towards the one in the public cluster based on when deployments were created.

**Pull request merged**
