### PR TITLE
Add a section of immunogenomics studies

### PR DESCRIPTION
**Pull request by yichaoS**
in the priority section of the query box
Fixing datahub issue: https://github.com/cBioPortal/datahub/issues/1133

### CODE REVIEW

**Comment by yichaoS** [comment]
@jjgao @inodb Could you please review this? Not sure how to test it in visualization.

**Comment by inodb** [comment]
@yichaoS Looks good to me

You can review it on the homepage by typing this in the console and refreshing

```
localStorage.frontendConfig = '{"serverConfig":{"priority_studies":"PanCancer Studies#msk_impact_2017,metastatic_solid_tumors_mich_2017,mixed_allen_2018,summit_2018,tmb_mskcc_2018,ntrk_msk_2019;Pediatric Cancer Studies#pptc_2019,all_phase2_target_2018_pub,rt_target_2018_pub,wt_target_2018_pub,aml_target_2018_pub,nbl_target_2018_pub,pediatric_dkfz_2017,mixed_pipseq_2017,all_stjude_2016,all_stjude_2015,es_dfarber_broad_2014,es_iocurie_2014,mbl_pcgp;Cell lines#ccle_broad_2019,cellline_ccle_broad,cellline_nci60;Immunogenomics#gbm_columbia_2019,skcm_dfci_2015,skcm_mskcc_2014,mel_ucla_2016,nsclc_mskcc_2018,nsclc_mskcc_2015,tmb_mskcc_2018,ccrcc_dfci_2019"}}'
```

Screen Shot 2020-09-10 at 6 42 30 PM


Make sure to clear again after

**Review by inodb — APPROVED** [review]

**Comment by yichaoS** [comment]
@inodb Thanks so much for the info!!

**Comment by jjgao** [comment]
Thanks, @yichaoS. Can we move the immunogenomics section before the celllines section?

**Comment by yichaoS** [comment]
@jjgao Adjusted the order, please see screenshot
Screen Shot 2020-09-18 at 3 51 12 PM

**Pull request merged**
